name: Compilar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar archivos
        uses: actions/checkout@v4

      - name: Preparar proyecto
        run: |
          mkdir proyecto
          unzip -q AforoTanque_GitHubCloud.zip -d proyecto

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.13'

      - name: Compilar APK
        run: |
          cd proyecto
          gradle assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: AforoTanque-APK
          path: proyecto/app/build/outputs/apk/debug/app-debug.apk