name: Compilar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar archivos
        uses: actions/checkout@v4

      - name: Preparar proyecto
        run: |
          mkdir proyecto
          unzip -q AforoTanque_GitHubCloud.zip -d proyecto

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.13'

     - name: Configurar Java 17
  run: |
    cd proyecto
    sed -i '/android {/a\
    compileOptions {\
        sourceCompatibility = JavaVersion.VERSION_17\
        targetCompatibility = JavaVersion.VERSION_17\
    }' app/build.gradle.kts
    sed -i '/android {/a\
    kotlinOptions {\
        jvmTarget = "17"\
    }' app/build.gradle.kts

- name: Compilar APK
  run: |
    cd proyecto
    gradle assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: AforoTanque-APK
          path: proyecto/app/build/outputs/apk/debug/app-debug.apk